//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_Nouns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Nouns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackEnd.Resources.Strings_Nouns", typeof(Strings_Nouns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora.
        /// </summary>
        public static string Noun_Aurora {
            get {
                return ResourceManager.GetString("Noun-Aurora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string Noun_Beach {
            get {
                return ResourceManager.GetString("Noun-Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear.
        /// </summary>
        public static string Noun_Bear {
            get {
                return ResourceManager.GetString("Noun-Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeze.
        /// </summary>
        public static string Noun_Breeze {
            get {
                return ResourceManager.GetString("Noun-Breeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brook.
        /// </summary>
        public static string Noun_Brook {
            get {
                return ResourceManager.GetString("Noun-Brook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canyon.
        /// </summary>
        public static string Noun_Canyon {
            get {
                return ResourceManager.GetString("Noun-Canyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade.
        /// </summary>
        public static string Noun_Cascade {
            get {
                return ResourceManager.GetString("Noun-Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert.
        /// </summary>
        public static string Noun_Desert {
            get {
                return ResourceManager.GetString("Noun-Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string Noun_Echo {
            get {
                return ResourceManager.GetString("Noun-Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame.
        /// </summary>
        public static string Noun_Flame {
            get {
                return ResourceManager.GetString("Noun-Flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grove.
        /// </summary>
        public static string Noun_Grove {
            get {
                return ResourceManager.GetString("Noun-Grove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbor.
        /// </summary>
        public static string Noun_Harbor {
            get {
                return ResourceManager.GetString("Noun-Harbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        public static string Noun_Infinity {
            get {
                return ResourceManager.GetString("Noun-Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island.
        /// </summary>
        public static string Noun_Island {
            get {
                return ResourceManager.GetString("Noun-Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagoon.
        /// </summary>
        public static string Noun_Lagoon {
            get {
                return ResourceManager.GetString("Noun-Lagoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meadow.
        /// </summary>
        public static string Noun_Meadow {
            get {
                return ResourceManager.GetString("Noun-Meadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meadow.
        /// </summary>
        public static string Noun_Meadow1 {
            get {
                return ResourceManager.GetString("Noun-Meadow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        public static string Noun_Mist {
            get {
                return ResourceManager.GetString("Noun-Mist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        public static string Noun_Moon {
            get {
                return ResourceManager.GetString("Noun-Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain.
        /// </summary>
        public static string Noun_Mountain {
            get {
                return ResourceManager.GetString("Noun-Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean.
        /// </summary>
        public static string Noun_Ocean {
            get {
                return ResourceManager.GetString("Noun-Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchard.
        /// </summary>
        public static string Noun_Orchard {
            get {
                return ResourceManager.GetString("Noun-Orchard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pebble.
        /// </summary>
        public static string Noun_Pebble {
            get {
                return ResourceManager.GetString("Noun-Pebble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petal.
        /// </summary>
        public static string Noun_Petal {
            get {
                return ResourceManager.GetString("Noun-Petal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pine.
        /// </summary>
        public static string Noun_Pine {
            get {
                return ResourceManager.GetString("Noun-Pine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string Noun_Rainbow {
            get {
                return ResourceManager.GetString("Noun-Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River.
        /// </summary>
        public static string Noun_River {
            get {
                return ResourceManager.GetString("Noun-River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapphire.
        /// </summary>
        public static string Noun_Sapphire {
            get {
                return ResourceManager.GetString("Noun-Sapphire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serenade.
        /// </summary>
        public static string Noun_Serenade {
            get {
                return ResourceManager.GetString("Noun-Serenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparrow.
        /// </summary>
        public static string Noun_Sparrow {
            get {
                return ResourceManager.GetString("Noun-Sparrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Noun_Star {
            get {
                return ResourceManager.GetString("Noun-Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starlight.
        /// </summary>
        public static string Noun_Starlight {
            get {
                return ResourceManager.GetString("Noun-Starlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string Noun_Sunset {
            get {
                return ResourceManager.GetString("Noun-Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquility.
        /// </summary>
        public static string Noun_Tranquility {
            get {
                return ResourceManager.GetString("Noun-Tranquility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string Noun_Tree {
            get {
                return ResourceManager.GetString("Noun-Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valley.
        /// </summary>
        public static string Noun_Valley {
            get {
                return ResourceManager.GetString("Noun-Valley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper.
        /// </summary>
        public static string Noun_Whisper {
            get {
                return ResourceManager.GetString("Noun-Whisper", resourceCulture);
            }
        }
    }
}
