//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Adjectives {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Adjectives() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackEnd.Resources.Strings_Adjectives", typeof(Strings_Adjectives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurous.
        /// </summary>
        internal static string Adjective_Adventurous {
            get {
                return ResourceManager.GetString("Adjective-Adventurous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        internal static string Adjective_Bright {
            get {
                return ResourceManager.GetString("Adjective-Bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charming.
        /// </summary>
        internal static string Adjective_Charming {
            get {
                return ResourceManager.GetString("Adjective-Charming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheerful.
        /// </summary>
        internal static string Adjective_Cheerful {
            get {
                return ResourceManager.GetString("Adjective-Cheerful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clever.
        /// </summary>
        internal static string Adjective_Clever {
            get {
                return ResourceManager.GetString("Adjective-Clever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courageous.
        /// </summary>
        internal static string Adjective_Courageous {
            get {
                return ResourceManager.GetString("Adjective-Courageous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cozy.
        /// </summary>
        internal static string Adjective_Cozy {
            get {
                return ResourceManager.GetString("Adjective-Cozy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative.
        /// </summary>
        internal static string Adjective_Creative {
            get {
                return ResourceManager.GetString("Adjective-Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious.
        /// </summary>
        internal static string Adjective_Curious {
            get {
                return ResourceManager.GetString("Adjective-Curious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determined.
        /// </summary>
        internal static string Adjective_Determined {
            get {
                return ResourceManager.GetString("Adjective-Determined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetic.
        /// </summary>
        internal static string Adjective_Energetic {
            get {
                return ResourceManager.GetString("Adjective-Energetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        internal static string Adjective_Friendly {
            get {
                return ResourceManager.GetString("Adjective-Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentle.
        /// </summary>
        internal static string Adjective_Gentle {
            get {
                return ResourceManager.GetString("Adjective-Gentle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genuine.
        /// </summary>
        internal static string Adjective_Genuine {
            get {
                return ResourceManager.GetString("Adjective-Genuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracious.
        /// </summary>
        internal static string Adjective_Gracious {
            get {
                return ResourceManager.GetString("Adjective-Gracious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        internal static string Adjective_Happy {
            get {
                return ResourceManager.GetString("Adjective-Happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonious.
        /// </summary>
        internal static string Adjective_Harmonious {
            get {
                return ResourceManager.GetString("Adjective-Harmonious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaginative.
        /// </summary>
        internal static string Adjective_Imaginative {
            get {
                return ResourceManager.GetString("Adjective-Imaginative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jovial.
        /// </summary>
        internal static string Adjective_Jovial {
            get {
                return ResourceManager.GetString("Adjective-Jovial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joyful.
        /// </summary>
        internal static string Adjective_Joyful {
            get {
                return ResourceManager.GetString("Adjective-Joyful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Adjective_Kind {
            get {
                return ResourceManager.GetString("Adjective-Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively.
        /// </summary>
        internal static string Adjective_Lively {
            get {
                return ResourceManager.GetString("Adjective-Lively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyal.
        /// </summary>
        internal static string Adjective_Loyal {
            get {
                return ResourceManager.GetString("Adjective-Loyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky.
        /// </summary>
        internal static string Adjective_Lucky {
            get {
                return ResourceManager.GetString("Adjective-Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic.
        /// </summary>
        internal static string Adjective_Optimistic {
            get {
                return ResourceManager.GetString("Adjective-Optimistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passionate.
        /// </summary>
        internal static string Adjective_Passionate {
            get {
                return ResourceManager.GetString("Adjective-Passionate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaceful.
        /// </summary>
        internal static string Adjective_Peaceful {
            get {
                return ResourceManager.GetString("Adjective-Peaceful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quirky.
        /// </summary>
        internal static string Adjective_Quirky {
            get {
                return ResourceManager.GetString("Adjective-Quirky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiant.
        /// </summary>
        internal static string Adjective_Radiant {
            get {
                return ResourceManager.GetString("Adjective-Radiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resourceful.
        /// </summary>
        internal static string Adjective_Resourceful {
            get {
                return ResourceManager.GetString("Adjective-Resourceful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincere.
        /// </summary>
        internal static string Adjective_Sincere {
            get {
                return ResourceManager.GetString("Adjective-Sincere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirited.
        /// </summary>
        internal static string Adjective_Spirited {
            get {
                return ResourceManager.GetString("Adjective-Spirited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquil.
        /// </summary>
        internal static string Adjective_Tranquil {
            get {
                return ResourceManager.GetString("Adjective-Tranquil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrant.
        /// </summary>
        internal static string Adjective_Vibrant {
            get {
                return ResourceManager.GetString("Adjective-Vibrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesome.
        /// </summary>
        internal static string Adjective_Wholesome {
            get {
                return ResourceManager.GetString("Adjective-Wholesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witty.
        /// </summary>
        internal static string Adjective_Witty {
            get {
                return ResourceManager.GetString("Adjective-Witty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zealous.
        /// </summary>
        internal static string Adjective_Zealous {
            get {
                return ResourceManager.GetString("Adjective-Zealous", resourceCulture);
            }
        }
    }
}
